[package]
name = "tut"
version = "0.1.0"
authors = ["rsherman <r.sherman@jayex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.11.1"